Handle no transcript exception
Some videos does not have transcript resulting in:
    subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']
KeyError: 'transcript'

Add try/exception